#!/usr/bin/env perl
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# ./script/spaghetti install host=localhost dbname=gitty \
# user=gitty password=secret

if ( $ARGV[0] eq 'install' )
{
    use Pony::Stash;
    
    # touch
    open F, '>./resources/stash.dat';
    print F '';
    close F;
    
    my $stash = Pony::Stash->new('./resources/stash.dat');
    my %conf;
    
    for my $conf ( @ARGV[1..4] )
    {
        %conf = ( %conf, split('=', $conf) );
    }
    
    $stash->set( database => \%conf );
    $stash->save;

    exit;
}

use Spaghetti::Defaults;

# Application
$ENV{MOJO_APP} ||= 'Spaghetti';

# Start commands
Mojolicious::Commands->start;
