#!/usr/bin/env perl

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

use Pony::Stash;
use Pony::Model::Dbh::MySQL;
use Stuff::Git::Gitolite;

    Pony::Stash->new('./resources/stash.dat');
    my $db = Pony::Stash->get('database');
    Pony::Model::Dbh::MySQL->new($db);
            
    Stuff::Git::Gitolite->new( shift @ARGV )->update;

1;
