
=pod

=head1 Prepare git user

Install soft. Run as root.

    aptitude install openssh-server git-core

    adduser --system --shell /bin/sh --gecos 'git version control' --group \
            --disabled-password --home /home/git git

Create ssh key for git.

    sudo -u git ssh-keygen

Allow ssh support for git. Edit manually file C</etc/ssh/sshd_config>. Add user
git into line "AllowUsers".

    /etc/init.d/ssh restart

=head1 Install gitolite

Run as root.

    aptitude install gitolite

Run as git.

    gl-setup ~/1.pub

Get admin repo (run as git-admin user).

    git clone git@server:gitolite-admin

=head1 Install spaghetti

    git clone git://github.com/h15/spaghetti.git
    cd ./spaghetti

MySQL

    mysql> CREATE DATABASE `spaghetti`;
    mysql> GRANT ALL PRIVILEGES ON spaghetti.* TO 'spaghetti'@'localhost' IDENTIFIED BY 'secret'  WITH GRANT OPTION;
    mysql> source /path/to/spaghetti/db.sql

Install dependencies

    cpan Mojolicious MIME::Lite Net::Akismet Pony::Object interface Git::Repository

    git clone git://github.com/h15/pony.git
    cd ./pony
    perl ./Build.PL
    ./Build install

Install cron task

    crontab -e

Write

    * * * * * ./script/updateGitolite /path/to/gitolite-admin

Install system

    perl ./script/spaghetti install host=localhost user=spaghetti \
        password=secret dbname=spaghetti

=head1 Run spaghetti

    nohup perl ./script/spaghetti daemon &

Open http://server:3000/

=head1 Make gitolite config and keys

    ./script/updateGitolite /path/to/gitolite-admin

=cut

